Force workspace volume to be emptyDir by default for pod templates
- In some cases, it is possible for the workspace volume to be set as a DynamicPVCWorkspaceVolume when
  the pod template is persisted when no workspace volume is specified.
- Some environments may not permit PVCs to be created on the fly and this can then result in:

Error in provisioning; agent=KubernetesSlave name: maven-q74tc, template=PodTemplate{inheritFrom='', name='maven', namespace='', label='maven', serviceAccount='jenkins', nodeSelector='', nodeUsageMode=NORMAL, workspaceVolume=org.csanchez.jenkins.plugins.kubernetes.volumes.workspace.DynamicPVCWorkspaceVolume@61839d72, containers=[ContainerTemplate{name='jnlp', image='docker.io/openshift/jenkins-agent-maven-35-centos7:v3.11', alwaysPullImage=true, workingDir='/tmp', command='', args='${computer.jnlpmac} ${computer.name}', resourceRequestCpu='', resourceRequestMemory='', resourceLimitCpu='', resourceLimitMemory='', livenessProbe=org.csanchez.jenkins.plugins.kubernetes.ContainerLivenessProbe@556c26f6}]}
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/cvp/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims "pvc-maven-q74tc" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>.